x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  # Frontend
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile-prod
      args:
        TIPTAP_PRO_TOKEN: ${TIPTAP_PRO_TOKEN}
    ports:
      - 3000:3000
    depends_on:
      - api
    hostname: "0.0.0.0"

  # Backend
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile-prod
    ports:
      - 5000:5000
    hostname: "0.0.0.0"
    restart: always
    depends_on:
      - server
      - workers
      - db
      - redis

  # Judge0
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - db
      - redis

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
