"""Init

Revision ID: 14263fb87c5b
Revises: 
Create Date: 2023-08-12 19:58:01.749873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14263fb87c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=320), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
