FROM python:3.11.9-slim

WORKDIR /
COPY .env .
COPY /api /api

WORKDIR /api
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["waitress-serve", "--port=5000", "--host=0.0.0.0", "index:app"]