name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: root
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script: |
            echo "$PWD"
            cd /root/sqil
            git pull
            docker compose build
            docker compose up
